### ISSUE TITLE
[BUG] ImportError when using comet-ml

### ISSUE THREAD

**Issue by amajidsinar** [nodefluxio/vortex#113]
**Describe the bug**
``ImportError: You must import Comet before these modules: torch, tensorboard`` is encountered when using comet-ml

**To Reproduce**

instantiate CometLogger with the required parameters and fit the model using the logger
```
comet_logger = CometLogger()
trainer = pl.Trainer(logger=comet_logger)
trainer.fit(model)
```

**Expected behavior**
Logging happens without error

**Screenshots**

**Solution**
Simply import `import comet_ml` at the very top of the training script, as suggested in this [post](https://github.com/PyTorchLightning/pytorch-lightning/issues/5829)

**Comment by alifahrri** [comment]
thanks @amajidsinar
