### ISSUE TITLE
[BUG] Error while import MetricBase

### ISSUE THREAD

**Issue by mrifkikurniawan** [nodefluxio/vortex#115]
**Describe the bug**
Error while import MetricBase class from /vortex/development/utils/profiler/lightning.py for creating metrics class.

**Expected behavior**
no error and success while calling the MetricBase class.

**Screenshots**
![Screenshot from 2021-06-21 15-56-46](https://user-images.githubusercontent.com/42391439/122735547-54dce200-d2a9-11eb-832c-be416c0bb5c6.png)

**Comment by triwahyuu** [comment]
PR in #114

**Comment by alifahrri** [comment]
thanks @mrifkikurniawan @triwahyuu
