### ISSUE TITLE
[BUG] output format is not defined

### ISSUE THREAD

**Issue by amajidsinar** [nodefluxio/vortex#66]
**Describe the bug**
NameError: name 'output_format' is not defined even though I had given the extra parameter `self.task` and `self.output_format`
inside the model at `nodeflux/face_detection/retinaface.py`

**To Reproduce**
clone git@gitlab.com:nodefluxio/rexxar-rg/inference-repository/face-detection.git into branch 2-export-to-vortex
run export.py

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26416205/92905607-fc410480-f44d-11ea-90d7-b9c698e99864.png)

**Additional context**
Done on v0.2

**Comment by alphinside** [comment]
where can i get the weights file? @amajidsinar

**Comment by triwahyuu** [comment]
can you send me the model definition and your `export.py` code? @amajidsinar

**Comment by amajidsinar** [comment]
@triwahyuu @alphinside sorry I forgot to mention that you need to run `sh retrieve_weight` to get the model. I just tried it and it worked without problem. But if it's not working you can download at `s3://nodeflux-data/nodeflux-zoo/object-detection/wide-area-face-detection_-_1-class/v1/mobilenet0.25_Final.pth`

@triwahyuu you can clone from here `git@gitlab.com:nodefluxio/rexxar-rg/inference-repository/face-detection.git into branch 2-export-to-vortex` on branch ` 2-export-to-vortex` as I've mentioned above

**Comment by triwahyuu** [comment]
so is it solved?

**Comment by amajidsinar** [comment]
@triwahyuu not yet

**Comment by triwahyuu** [comment]
okay, on it

**Comment by amajidsinar** [comment]
@triwahyuu cool, thanks a bunch
