### ISSUE TITLE
[BUG] Dataset is not registered

### ISSUE THREAD

**Issue by amajidsinar** [nodefluxio/vortex#83]
**Describe the bug**
Dataset cannot be registered

**To Reproduce**
1. Pull latest image from docker pull nodefluxio/vortex:latest
2. Download dataset from https://gitlab.com/nodefluxio/dataset-repository/image-classification/liveness
3. $ vortex
**Expected behavior**
Liveness dataset is registered

**Screenshots**
![image](https://user-images.githubusercontent.com/26416205/98788707-e17e1280-2433-11eb-8100-4fefd8672728.png)

**Additional context**

**Comment by triwahyuu** [comment]
I haven't reproduce your issue, but can I know where did you put your dataset?

**Comment by amajidsinar** [comment]
You can get the dataset from [here]( https://gitlab.com/nodefluxio/dataset-repository/image-classification/liveness)

**Comment by triwahyuu** [comment]
no no, I mean the path where you put the dataset inside the docker container.  
currently the dataset only reads in `external/datasets` relative to where you call the vortex cli. you can also put your dataset directory path to an environment variable, but I forgot the name of the variable, let me look it up.

**Comment by triwahyuu** [comment]
the environment variable name is `VORTEX_DATASET_ROOT`

**Comment by amajidsinar** [comment]
im sorry i got it all wrong. i put it in `external/datasets` as mentioned on the docs

![image](https://user-images.githubusercontent.com/26416205/98797916-d0d39980-243f-11eb-90e3-a2ffa34ed157.png)

**Comment by triwahyuu** [comment]
ohh I see, let me try to reproduce it tonight then.

**Comment by triwahyuu** [comment]
I found the problem, it is your dataset that doesn't meet vortex's requirement.  
To be found by vortex, your dataset definition should contain 3 things at the same file: dataset class definition, `supported_dataset` variable (list) which describes all of the available dataset class in the file, and `create_dataset` function that which returns the dataset object.  

I have fixed your implementation and made a PR on it. check it out.

**Comment by triwahyuu** [comment]
I think we need to add support for dataset registration decorator, cc @alifahrri

**Comment by amajidsinar** [comment]
@triwahyuu thanks a bunch! I'd check on it

**Comment by amajidsinar** [comment]
Works like a charm. Thanks a lot!
